source("~/Programmes/fonctionsR/r2asciidoc/misc.r")
source("~/Programmes/fonctionsR/r2asciidoc/class.r")
source("~/Programmes/fonctionsR/r2asciidoc/generic.r")
source("~/Programmes/fonctionsR/r2asciidoc/show.r")
source("~/Programmes/fonctionsR/r2asciidoc/asciiDataFrame.r")
source("~/Programmes/fonctionsR/r2asciidoc/asciiVector.r")
