#!/bin/sh

echo "library(ascii); Asciidoc(\"index.Rnw\") ; T2t(\"t2t.Rnw\") ; Org(\"org.Rnw\") ; Sphinx(\"sphinx.Rnw\")" | R --no-save --no-restore || { echo "Probleme dans Sweave() | R..." >&2; exit 1; }
sphinx-build -b html . sphinx/html
cd sphinx/html
sphinx-to-github
cd ../..
txt2tags -t html t2t.t2t
# Comment faire pour org ?
#asciidoc -a toc -a linkcss -a stylesheet=latex.css -a stylesdir=. index.txt 
asciidoc -a toc index.txt 
asciidoc -b docbook index.txt
dblatex -T db2latex index.xml
docbook2odf -f index.xml
