#!/bin/sh

echo "library(ascii); Asciidoc(\"index.Rnw\") ; T2t(\"t2t.Rnw\") ; Org(\"org.Rnw\") ; ReST(\"rest.Rnw\")" | R --no-save --no-restore || { echo "Probleme dans Sweave() | R..." >&2; exit 1; }
./rst2html-highlight --stylesheet-path=pygments-default.css -s rest.rst rest.html
txt2tags -t html t2t.t2t
# Comment faire pour org ?
#asciidoc -a toc -a linkcss -a stylesheet=latex.css -a stylesdir=. index.txt 
asciidoc -a toc index.txt 
asciidoc -b docbook index.txt
dblatex -T db2latex index.xml
#docbook2odf -f index.xml
