#!/bin/sh

echo "library(ascii); Sweave(\"index.Rnw\", RweaveAsciidoc)" | R --no-save --no-restore || { echo "Probleme dans Sweave() | R..." >&2; exit 1; }
#asciidoc -a toc -a linkcss -a stylesheet=compact.css -a stylesdir=. index.txt 
asciidoc -a toc index.txt 
asciidoc -b docbook index.txt
dblatex index.xml
docbook2odf -f index.xml
